<?php

namespace ContainerIafxDCP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M7ecLKhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m7ecLKh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m7ecLKh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'userRepository' => ['privates', 'App\\Core\\Product\\Repository\\UserRepository', 'getUserRepository2Service', true],
        ], [
            'userRepository' => 'App\\Core\\Product\\Repository\\UserRepository',
        ]);
    }
}
