<?php

namespace ContainerX4QlfTX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2MKwkl1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2MKwkl1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2MKwkl1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'requestDto' => ['privates', 'App\\Api\\User\\Dto\\ProductUpdateRequestDto', 'getUserUpdateRequestDtoService', true],
            'userRepository' => ['privates', 'App\\Core\\Product\\Repository\\ProductRepository', 'getUserRepositoryService', true],
            'validationErrors' => ['privates', '.errored..service_locator.2MKwkl1.Symfony\\Component\\Validator\\ConstraintViolationListInterface', NULL, 'Cannot autowire service ".service_locator.2MKwkl1": it references interface "Symfony\\Component\\Validator\\ConstraintViolationListInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'requestDto' => 'App\\Api\\User\\Dto\\ProductUpdateRequestDto',
            'userRepository' => 'App\\Core\\Product\\Repository\\ProductRepository',
            'validationErrors' => 'Symfony\\Component\\Validator\\ConstraintViolationListInterface',
        ]);
    }
}
